spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

myapp:
  randomSequenceLength: 6

server:
  port: 8081  # Porta principal do aplicativo
management:
  server:
    port: 8082  # Porta de administração (configuração opcional)